[program:survey_app]
command=/var/www/survey_app/venv/bin/streamlit run /var/www/survey_app/app.py --server.port=5000
directory=/var/www/survey_app
user=www-data
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stderr_logfile=/var/log/survey_app/streamlit.err.log
stdout_logfile=/var/log/survey_app/streamlit.out.log